name: Execute Tests
on:
  push:
  workflow_dispatch:

jobs:

  goat-prepare:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout GOAT
      uses: actions/checkout@v3

    - name: Checkout Terraform AWS Provider
      uses: actions/checkout@v3
      with:
        repository: hashicorp/terraform-provider-aws
        path: './terraform-provider-aws'

    - name: Install dependancies
      run: |
        make install

    - id: set-matrix
      run: echo "::set-output name=matrix::$(python main.py list-services)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    - name: Get Release Date
      run: |
        echo "RELEASE_DATE=`date '+%D'`" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_DATE }}
        release_name: Release ${{ env.RELEASE_DATE }}
        draft: false
        prerelease: false  

  goat:
    needs: goat-prepare
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.goat-prepare.outputs.matrix) }}
    runs-on: ubuntu-latest
    env:
      DNS_ADDRESS: 0
      AWS_DEFAULT_REGION: us-east-2
      AWS_ALTERNATE_REGION: eu-west-1

    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'

    - name: Checkout goat
      uses: actions/checkout@v3

    - name: Checkout Localstack
      uses: actions/checkout@v3
      with:
        repository: localstack/localstack
        path: './localstack'

    - name: Checkout Terraform AWS Provider
      uses: actions/checkout@v3
      with:
        repository: hashicorp/terraform-provider-aws
        path: './terraform-provider-aws'

    - name: Cache Python .venv
      id: python-cache
      uses: actions/cache@v2
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/setup.cfg') }}

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install libsasl2-dev -y
        pip install --upgrade pip
        pip install pyyaml
        make install

    - name: Installing Localstack Dependancies and Start Localstack
      working-directory: ./localstack
      run: |
        make install
        make start &

    - name: Check Localstack Endpoint
      uses: jtalk/url-health-check-action@v2
      with:
        url: http://localhost:4566
        max-attempts: 30
        retry-delay: 5s
        retry-all: true

    - name: Patch Terraform Provider
      working-directory: ./terraform-provider-aws
      run: |
        git apply ../etc/tf-patch/0001-endpoints.patch

    - name: Cache Go dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/terraform-provider-aws/go.sum') }}

    - name: Test Cases Scrape
      run: python main.py scrape

    - name: Running Test Cases
      run: python main.py run -s ${{ matrix.service }} -f

    - name: Generate Report
      run: python main.py report

    - name: Create ${{ matrix.service }} Zip file 
      run: |
        mv report.html report-${{ matrix.service }}.html
        zip -r ${{ matrix.service }}.zip ./logs/${{ matrix.service }} report-${{ matrix.service }}.html

    - name: Upload Release Asset - ${{ matrix.service }}
      id: upload-release-asset-${{ matrix.service }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ matrix.service }}.zip
        asset_name: ${{ matrix.service }}.zip
        asset_content_type: application/zip